[workspace]
members = [
  "gst-meet",
  "lib-gst-meet",
  "lib-gst-meet-c",
  "nice-gst-meet",
  "nice-gst-meet-sys",
  "jitsi-xmpp-parsers",
]

[patch.crates-io]
jid = { git = "https://gitlab.com/xmpp-rs/xmpp-rs.git" }
minidom = { git = "https://gitlab.com/xmpp-rs/xmpp-rs.git" }
